### ISSUE TITLE
Action! problem

### ISSUE THREAD

**Issue by pedromagician** [matosimi/atari-fontmaker#1]
Bad font export to Action!
Correct should be

```
PROC FontMain=*() [
  .......
]
```

**Comment by matosimi** [comment]
@CycoPH do you have any experience with action!? ...because i have not.
I can blindly do the change. What do you think?

**Comment by CycoPH** [comment]
Nope, never used it.

**Comment by CycoPH** [comment]
But I did find this:
PROC FONTS1=*()
[
...
]
@ https://github.com/zbyti/a8-action-scramble/blob/master/src/ASSETS.ACT

I'll change the procedure format and publish a new version

**Comment by CycoPH** [comment]
Latest version 1.6.8.0 has this fixed
