### ISSUE TITLE
inverse color chars - editing

### ISSUE THREAD

**Issue by matosimi** [matosimi/atari-fontmaker#3]
I think it would be good to show/use the inverse color COLPF3 in the character editor when editing inverse chars ( > $80)

what do you think?
![image](https://github.com/matosimi/atari-fontmaker/assets/5637705/22e008df-c0f0-4ab6-9629-c5485971ff60)

**Comment by CycoPH** [comment]
Very good idea.  It has been implemented in V1.6.9.0
