### ISSUE TITLE
Selecting font2 3 or 4, and drawing in view window not working for me

### ISSUE THREAD

**Issue by drarem** [matosimi/atari-fontmaker#4]
Can only draw in the view editing window with font1. If i select font2, draw it then update the font it still only shows font 1.  Might be a bug?

**Comment by CycoPH** [comment]
Did you switch the display font by clicking on the column of 1s next to the view window?
![image](https://github.com/matosimi/atari-fontmaker/assets/2360950/8b1296c8-bea4-4777-aefe-f3c23a6a29dd)

**Comment by drarem** [comment]
The columns do the trick, thanks.
