### ISSUE TITLE
Add support for Mode 5 (40x12)

### ISSUE THREAD

**Issue by EricCarrGH** [matosimi/atari-fontmaker#8]
I've really enjoyed this tool the past few years and recently have a project in MODE5 (40x12) and really wanted to see the proper aspect ratio of the view, so I modifed the code to add support for MODE5.

Pull Request here : https://github.com/matosimi/atari-fontmaker/pull/7

Clicking "Change GFX" now switches between Mode 0, 4, and 5.

It basically draws each character twice as high in the view, resulting in showing the first 13 rows of the view.

Changes:

- Save/Restore of view remembers the new mode ``"ColoredGfx": "2"``
- View switches to 13 rows instead of 26
- Font selection on the view row spaced to 13 rows
- Cursor and Mega copy shows correct aspect ratio in view
- Character editor shows correct aspect ratio

<img width="1176" alt="Screenshot 2024-11-24 at 12 23 53 PM" src="https://github.com/user-attachments/assets/a22eb598-b771-4faf-8ba1-04575c83f2c7">

**Comment by matosimi** [comment]
👌i will look into this...

**Comment by matosimi** [comment]
merged
